#!/bin/bash

# Update package lists and install Nginx
sudo apt update
sudo apt install nginx -y

# Configure custom HTTP response header
echo 'server_tokens off;
        add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx
