#!/bin/bash

sudo apt update
sudo apt install nginx -y
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo systemctl restart nginx
sudo systemctl status nginx | grep 'Active:'
