#!/usr/bin/env bash
# This script installs and configures Nginx to listen on port 80

# Update package lists and install Nginx
apt-get update -y
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen [::]:80 default_server;/listen [::]:80;/g' /etc/nginx/sites-available/default

# Restart Nginx service if not running
if ! systemctl is-active --quiet nginx; then
    systemctl restart nginx
fi
